GET http://localhost:9999/ping
Content-Type: application/json
###


POST http://localhost:9999/clientes/1/transacoes
Content-Type: application/json

{
    "valor": 20,
    "tipo" : "c",
    "descricao" : "descricao"
}
### Expected 200

POST http://localhost:9999/clientes/1/transacoes
Content-Type: application/json

{
    "valor": 150,
    "tipo" : "d",
    "descricao" : "descricao"
}
### Expected 200 When Have Limit
### Expected 422 When Have No Limit

POST http://localhost:9999/clientes/10/transacoes
Content-Type: application/json

{
    "valor": 150,
    "tipo" : "d",
    "descricao" : "descricao"
}
### Expected 200 When Have Limit
### Expected 422 When Have No Limit